import type { SubscriberData } from "@/components/User/UserRoot"

export async function getInscritos(): Promise<SubscriberData[]> {
	// Simulating a delay of 1 second
	await new Promise((resolve) => setTimeout(resolve, 2000))

	return [
		{
			name: "Maria Silva Santos",
			email: "maria.silva@ccc.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 8.5,
			mediaIndividual: 8.7,
			mediaGrupo: 8.3,
			mediaEntrevista: 9.0,
			mediaMembro: 8.8,
			mediaFinal: 8.5,
		},
		{
			name: "João Oliveira Lima",
			email: "joao.oliveira@dsc.ufcg.edu.br",
			status: "Reprovado",
			mediaApresentacao: 4.2,
			mediaIndividual: 4.0,
			mediaGrupo: 4.5,
			mediaEntrevista: 3.8,
			mediaMembro: 4.3,
			mediaFinal: 4.2,
		},
		{
			name: "Ana Beatriz Costa",
			email: "ana.costa@ee.ufcg.edu.br",
			status: "Pendente",
			mediaApresentacao: 6.8,
			mediaIndividual: 7.0,
			mediaGrupo: 6.5,
			mediaEntrevista: 7.2,
			mediaMembro: 6.9,
			mediaFinal: 6.8,
		},
		{
			name: "Carlos Eduardo Ferreira",
			email: "carlos.ferreira@computacao.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 9.1,
			mediaIndividual: 9.3,
			mediaGrupo: 8.9,
			mediaEntrevista: 9.5,
			mediaMembro: 9.2,
			mediaFinal: 9.1,
		},
		{
			name: "Juliana Mendes Almeida",
			email: "juliana.mendes@pet.ufcg.edu.br",
			status: "Pendente",
			mediaApresentacao: 7.5,
			mediaIndividual: 7.7,
			mediaGrupo: 7.2,
			mediaEntrevista: 7.8,
			mediaMembro: 7.6,
			mediaFinal: 7.5,
		},
		{
			name: "Pedro Henrique Santos",
			email: "pedro.santos@ccc.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 8.9,
			mediaIndividual: 9.1,
			mediaGrupo: 8.7,
			mediaEntrevista: 9.3,
			mediaMembro: 9.0,
			mediaFinal: 8.9,
		},
		{
			name: "Fernanda Oliveira Costa",
			email: "fernanda.oliveira@dsc.ufcg.edu.br",
			status: "Reprovado",
			mediaApresentacao: 3.7,
			mediaIndividual: 3.5,
			mediaGrupo: 4.0,
			mediaEntrevista: 3.3,
			mediaMembro: 3.8,
			mediaFinal: 3.7,
		},
		{
			name: "Lucas Rodrigues Silva",
			email: "lucas.rodrigues@ee.ufcg.edu.br",
			status: "Pendente",
			mediaApresentacao: 6.5,
			mediaIndividual: 6.7,
			mediaGrupo: 6.2,
			mediaEntrevista: 6.9,
			mediaMembro: 6.6,
			mediaFinal: 6.5,
		},
		{
			name: "Mariana Souza Lima",
			email: "mariana.souza@computacao.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 9.3,
			mediaIndividual: 9.5,
			mediaGrupo: 9.1,
			mediaEntrevista: 9.7,
			mediaMembro: 9.4,
			mediaFinal: 9.3,
		},
		{
			name: "Rafael Almeida Santos",
			email: "rafael.almeida@pet.ufcg.edu.br",
			status: "Pendente",
			mediaApresentacao: 7.2,
			mediaIndividual: 7.4,
			mediaGrupo: 6.9,
			mediaEntrevista: 7.5,
			mediaMembro: 7.3,
			mediaFinal: 7.2,
		},
		{
			name: "Camila Ferreira Oliveira",
			email: "camila.ferreira@ccc.ufcg.edu.br",
			status: "Reprovado",
			mediaApresentacao: 4.8,
			mediaIndividual: 4.6,
			mediaGrupo: 5.1,
			mediaEntrevista: 4.4,
			mediaMembro: 4.9,
			mediaFinal: 4.8,
		},
		{
			name: "Gabriel Costa Silva",
			email: "gabriel.costa@dsc.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 8.7,
			mediaIndividual: 8.9,
			mediaGrupo: 8.5,
			mediaEntrevista: 9.1,
			mediaMembro: 8.8,
			mediaFinal: 8.7,
		},
		{
			name: "Isabela Santos Pereira",
			email: "isabela.santos@ccc.ufcg.edu.br",
			status: "Aprovado",
			mediaApresentacao: 9.0,
			mediaIndividual: 9.2,
			mediaGrupo: 8.8,
			mediaEntrevista: 9.4,
			mediaMembro: 9.1,
			mediaFinal: 9.0,
		},
	]
}
